### PR TITLE
Active nav

### PR DESCRIPTION
**Pull request by walmarek**
- renemed ActorSaga.js
- active path fixed
Please review if is all fine.

### CODE REVIEW

**Review by MariolaFilipiak — APPROVED** [review]
Good!

**Review by MariolaFilipiak — APPROVED** [review]
seriously? Was the problem here?  :D
Good Job!

**Comment by walmarek** [comment]
The <Route path={toMovie(":id")}> in NavigationBar should be above <Route path={toMovies()}> and added "/movies/" in toMovie route.js. Did exacly the same with <Route path={toActor(":id")}>
 So ready to merge?

**Comment by xxFino** [comment]
Good job!

**Pull request merged**
